[target.'cfg(target_os = "macos")']
rustflags = [
    "-C",
    "link-args=-Wl,-rpath,@executable_path/../lib,-rpath,@executable_path,-rpath,@executable_path/../../../build",
]

[target.'cfg(not(target_os = "macos"))']
rustflags = [
    "-C",
    "link-args=-Wl,-rpath,\\$$ORIGIN/../lib,-rpath,\\$$ORIGIN,-rpath,\\$$ORIGIN/../../../build",
]
