name: vet OSS Components

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  # Required for actions/checkout@v4
  contents: read

  # Required for writing pull request comment
  issues: write
  pull-requests: write

  # For uploading SARIF report
  security-events: write

jobs:
  # https://github.com/safedep/vet
  vet:
    name: vet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Run vet
        id: vet
        uses: safedep/vet-action@v1
        with:
          policy: .github/vet/policy.yaml
          exception-file: .github/vet/exceptions.yml

          # Allow vet commenting in PR for Summary
          # https://github.com/safedep/vet-action?tab=readme-ov-file#configuration
          enable-comments-proxy: true
        env:
          # Required for writing pull request comment
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload SARIF report to GitHub for showing findings in centralized location in Security Tab
      - name: Upload SARIF
        if: steps.vet.outputs.report != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.vet.outputs.report }}
          category: vet
